// Each project card is rendered from this array — add a project by adding an entry.
// status: 'live' | 'building' | 'planning' | 'archive'
// button: label of the primary action; use disabled: true for non-clickable buttons.
export const projects = [
  {
    id: 'adventure',
    status: 'live',
    title: '오늘의 모험',
    description: 'A daily adventure app that transforms small tasks into meaningful quests.',
    story: 'I wanted everyday routines to become adventures for my son.',
    tags: ['React', 'PWA', 'Education', 'Family'],
    image: null,
    button: 'Open App',
    url: '/adventure',
  },
  {
    id: 'writing',
    status: 'live',
    title: '하루문장',
    description: 'A quiet place to write one sentence every day.',
    story: 'Writing one sentence is often easier than writing an entire page.',
    tags: ['Writing', 'Journal', 'Reflection'],
    image: null,
    button: 'Open App',
    url: '/writing',
  },
  {
    id: 'lumloom',
    status: 'live',
    title: 'Lumloom',
    description: 'The home of every project built under Lumloom.',
    story: 'Every project deserves a thoughtful home.',
    tags: ['Brand', 'Website', 'Design'],
    image: null,
    button: 'Current Page',
    url: '',
    disabled: true,
  },
  {
    id: 'knowledge-garden',
    status: 'building',
    title: 'Knowledge Garden',
    description: 'A searchable collection of notes and ideas.',
    story: 'Knowledge should grow, not disappear inside folders.',
    tags: ['Obsidian', 'Quartz', 'Knowledge'],
    image: null,
    button: 'Coming Soon',
    url: '',
    disabled: true,
  },
  {
    id: 'finance-companion',
    status: 'planning',
    title: 'Finance Companion',
    description: 'Thoughtful accounting and finance tools.',
    story: 'Work should feel simpler, not heavier.',
    tags: ['Accounting', 'Finance', 'Tools'],
    image: null,
    button: 'Coming Soon',
    url: '',
    disabled: true,
  },
  {
    id: 'ai-workspace',
    status: 'planning',
    title: 'AI Workspace',
    description: 'A growing collection of AI workflows and practical tools.',
    story: 'AI should reduce friction, not create complexity.',
    tags: ['AI', 'Automation', 'Workflow'],
    image: null,
    button: 'Coming Soon',
    url: '',
    disabled: true,
  },
];
